name: CI - Cypress Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: http://localhost:3000

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Instalar wait-on
        run: npm install -g wait-on

      - name: Subir servidor
        run: npx serverest &

      - name: Esperar servidor
        run: wait-on http://localhost:3000

      - name: Rodar testes
        run: npx cypress run
        continue-on-error: true

      - name: Gerar relatório
        if: always()
        run: npm run cy:report

      - name: Publicar relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report